### ISSUE TITLE
Opening Electry/VitaGrafixPatchlist repo crashes RepoHub

### ISSUE THREAD

**Issue by d-rez** [robDevs/Repo-Explorer#27]
Steps to reproduce:

* Star the repo under your account: https://github.com/Electry/VitaGrafixPatchlist 
* In RepoHub 0.2, go to Starred, click Patch list
* App crashes

**Comment by robDevs** [comment]
I was able to reproduce this issue on my device and will begin looking into the problem.

**Comment by robDevs** [comment]
This has been resolved in latest release.

**Comment by d-rez** [comment]
Cheers, thanks! Will update and check :)
